<?php
// Generated by the ShopHaat installer on 2026-09-04 20:50:45.
// Do not share this file. Keep it outside version control.
return array (
  'host' => 'localhost',
  'name' => 'shopdb',
  'user' => 'shopuser',
  'pass' => 'shoppass123',
  'port' => 3306,
  'charset' => 'utf8mb4',
);
